//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickZip_BankAngular.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBulkUserUploadCheck
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordKey { get; set; }
        public string PhoneNumber { get; set; }
        public string UserType { get; set; }
        public string Email { get; set; }
        public long ActivityId { get; set; }
        public string Remarks { get; set; }
        public long EntityId { get; set; }
        public string AppId { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
