//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickZip_BankAngular.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEntityFinancialDetail
    {
        public long FinancialDetailsId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> BankMasterId { get; set; }
        public string PAN_No { get; set; }
        public string TAN_No { get; set; }
        public string GSTIN_No { get; set; }
        public string BillingAddress { get; set; }
        public string ChargeDebitAcNo { get; set; }
        public string BankCorporateId { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public string IFSC { get; set; }
        public Nullable<long> RegionalManagerId { get; set; }
        public Nullable<long> PSM { get; set; }
        public string BillingContactPerson { get; set; }
        public string Designation { get; set; }
        public string ContactNo { get; set; }
        public string FaxNo { get; set; }
        public Nullable<int> ArrangementInDays { get; set; }
        public string PickUpLocationAddress { get; set; }
        public string PickUpContactPerson { get; set; }
        public string CommunicationMailPrimary { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> BusinessSegmentId { get; set; }
        public Nullable<long> SettlementTypeId { get; set; }
    }
}
