//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickZip_BankAngular.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMailMsgTransaction
    {
        public long TableID { get; set; }
        public string MandateID { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsMail { get; set; }
        public bool IsSMS { get; set; }
        public System.DateTime SendOn { get; set; }
    }
}
