//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickZip_BankAngular.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNPCIResponse_RBL
    {
        public long ResponseID { get; set; }
        public string FileNo { get; set; }
        public string UMRN { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int UploadID { get; set; }
    }
}
